version: '2.4'
services:
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Admin357/
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin357/
      MYSQL_DATABASE: loja_games
    ports:
      - "3308:3306"
    networks:
      - generation-network
  api_delojadegames:
    restart: always
    build: ./api_delojadegames
    working_dir: /api_delojadegames
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./api_delojadegames:/api_delojadegames
      - ~/.m2:/root/.m2
    ports:
      - "9000:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - generation-network
networks:
    generation-network:
        driver: bridge